mem 0 + 10 . // counter
mem 1 + 0 . // first
mem 2 + 1 . // second
mem 3 + 0 . // temp

// breaks after number 255 because we're using bytes :)
while mem dup , dup 0 > do
    1 - .
    mem 3 + mem 1 + , mem 2 + , + . // sum two numbers and put result in temp value
    mem 1 + mem 2 + , . // put second number in place of first
    mem 2 + mem 3 + , . // put temp value in place of second
    mem 3 + , dump // print
end
