macro BYTE 8 ;

macro first mem ;
macro second mem BYTE + ;
macro temp mem BYTE BYTE + + ;

first  0 !64 // first
second 1 !64 // second
temp   0 !64 // temp

20 0 while 2dup > do
    1 +
    temp first @64 second @64 + !64 // sum two numbers and put result in temp value
    first second @64 !64 // put second number in place of first
    second temp @64 !64 // put temp value in place of second
    temp @64 dump // print
end
